---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t hipages/rabbitmq:latest .
      - run: npx -p semantic-release-docker -p semantic-release -- semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
